# Generated by Django 3.2.6 on 2021-10-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='map',
        ),
        migrations.AddField(
            model_name='map',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
        ),
    ]
