# Generated by Django 3.2.6 on 2021-10-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20211002_1500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('portrait_url', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generate_island_name', max_length=20)),
                ('treasures', models.IntegerField(default=1)),
                ('defenses', models.IntegerField(default=0, null=True)),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hex')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('treasures', models.IntegerField(default=0)),
                ('ships', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('hex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hex')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
            ],
        ),
    ]
