# Generated by Django 3.2.7 on 2021-10-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211002_1500'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='q',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='island',
            name='r',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='island',
            name='s',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='api.map'),
        ),
    ]
