# Generated by Django 3.2.7 on 2021-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211003_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='hex',
        ),
        migrations.RemoveField(
            model_name='island',
            name='hex',
        ),
        migrations.AddField(
            model_name='fleet',
            name='q',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='r',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='s',
            field=models.IntegerField(null=True),
        ),
    ]
