# Generated by Django 3.2.7 on 2021-10-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211003_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
    ]
